# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2de1b3f80395954d3c7cb8eb683534efb74d792f32ec214fdcbfff1168771c0b26436965597e2d20d38fe7e7f8004ce2183347cd18d55e0496e65c290398a4ca

test:
  secret_key_base: b2500fd90bd527978bd76966bee227f93ccd3208b245b9e9a362bf0305b93f865a3bbb756d59ba7f05594aee9110addbb454f06636ed0239d952dbab49d2e181

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
